version: '3'
services:
  reverse-proxy:
    image: nginx
    depends_on:
      - test-identity-api-1
      - test-identity-api-2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443

  test-identity-api-1:
    image: test-identity-api:latest
    environment:
      ASPNET_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      TestIdentity_ConnectionStrings__RedisConn: "redis:6379,name=TestIdentity"
      TestIdentity_ConnectionStrings__Default: ${CONNECTION_STRING}
    depends_on:
      - redis
    links:
      - redis

  test-identity-api-2:
    image: test-identity-api:latest
    environment:
      ASPNET_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      TestIdentity_ConnectionStrings__RedisConn: "redis:6379,name=TestIdentity"
      TestIdentity_ConnectionStrings__Default: ${CONNECTION_STRING}
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis:3.0